name: testSpark
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testspark
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-02 12:55:49'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-02 12:55:49'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-02 12:55:49'
  udfs:
    udfs/f1_1:
      name: f1_1
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: kiranadmin@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    udfs/f1_2:
      name: f1_2
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: kiranadmin@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-02T12:55:49.391874Z'
  name: plibMaven
  version: 8.0.29
  id: '79073684'
  createdAt: '2024-08-02T12:55:49.391874Z'
  type: plibMaven
- modifiedAt: '2024-08-02T12:55:49.391874Z'
  name: plibPypi
  version: 1.9.9
  id: '2106439919'
  createdAt: '2024-08-02T12:55:49.391874Z'
  type: plibPypi
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.2.25.dev1
    isDefault: true
    author: null
    createdAt: '2024-08-02 12:55:40'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-02 12:55:40'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
